name: flutter_media_notification
version: 1.2.7
description: Flutter Media Notification helps you to show your media notification and control streaming media beyond your flutter app.
homepage: https://github.com/amosogra/flutter_media_notification

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.tarafdari.flutter_media_notification
    pluginClass: FlutterMediaNotificationPlugin